global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dcgm-exporter"
    static_configs:
      - targets: ["192.168.0.1:9400"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.0.1:9100"]
